### ISSUE TITLE
multiple airmega's not populating

### ISSUE THREAD

**Issue by kyl3n** [aschaper/homebridge-airmega#4]
In a situation where you have multiple Airmega's it's not populating all of the airmega's in HomeKit. Debug logs is just showing that one room is found. 

I tried to fork your project, but I keep having an issue trying to get typescript to compile...

 looking at this bit of code specifically >

authenticator.login(username, password).then(purifiers => {
          purifiers.forEach(purifier => this.registerAccessory(purifier, config));
          // Need to see what shows up under this purifier method, possibly an issue with the forEach loop here?
        });

If you need to use my airmega account login/password for an example JSON return for just let me know and I will let you use it.

**Comment by aschzero** [comment]
Thanks for letting me know about this issue! Since I don't have multiple purifiers to test with I'll need some help, but hopefully this can be resolved without needing your credentials. I just released an update (v3.1.6) containing additional debug logging when the purifiers are being retrieved. Please update and add the line `"debug": true` to your homebridge config (if you haven't already) and leave a comment with the log output. Thanks!

I am also curious to know more about the issues you're running into when getting the typescript to compile if you feel like giving more info about that. I'd be happy to help any way I can. :)

**Comment by kyl3n** [comment]
Alright so the issue is that the CWIL0100.json endpoint does not return all thermostats registered to the account. Using the additional log output that you added I just receive what you would receive when you have one air purifier on the account...

So I fired up Charles proxy to see why its doing this. The reason is that in their app, when you have multiple purifiers you can only select one purifier on your active screen. So this is why that endpoint is only showing one purifier, because it's the currently selected purifier. If you want to switch to another purifier you must select that purifier in the top right of the app.  Below I listed the endpoint which will show all of the purifiers. 

The endpoint that will list all of the purifiers attached to the account is:
CWIG0304.json

If you have an email or something, I can send the Charles logs to you.

Cheers

**Comment by aschzero** [comment]
Ah good catch! This is extremely helpful, thank you. I'm able to see that endpoint in Charles and the response looks very similar to the endpoint currently being used, so it should be pretty straightforward to update the plugin. I'll try it out and will keep you posted.

**Comment by aschzero** [comment]
@kyl3n I was able to get it working with the new endpoint and I did some testing with a fake response containing multiple purifiers to ensure all of the accessories show up and function correctly. I just published version `3.1.7-beta` with these changes – when you have some time, would you mind updating to this version and poke around a bit to make sure it works well? Thanks!

**Comment by kyl3n** [comment]
Hey, thanks for the quick fix. I finally had some time to test it overnight last night. Everything has appeared to work fine so far. Nice job. 

One thing I noticed when you move the fan speed slider, I hear an initial ring sound when the purifier changes fan speeds, followed by two more ring sounds. Is the purifier receiving multiple speed changes for some reason? Not really an issue, but I'm just wondering if you know why it's doing this. 

I really wish we had a way for local communication with these Airmega purifiers!

**Comment by aschzero** [comment]
That's great to hear, thanks for trying it out and verifying! I'll include the changes in the next release, hopefully in the next day or so.

I've noticed the same behavior regarding the fan speed adjustment, and it looks like the Home app sends multiple requests to the purifier while the slider is being actively adjusted. I've been wanting to get around to this so I'll also include a fix for this in the next release.

Completely agree with you about wanting local communication instead of going through the API. I'm only just starting to look into that but it's definitely a goal to have in the near future. :)

**Comment by aschzero** [comment]
`v3.1.7` is now available and includes the fixes for multiple purifier discovery as well as the fan speed adjustment issue ([full release notes](https://github.com/aschzero/homebridge-airmega/releases/tag/v3.1.7)). Thanks again for bringing these to my attention and for testing the changes! I'll go ahead and close this issue but feel free to re-open or create a new issue for anything else you come across.
